export const books = [
  {
    id: 'about',
    //number: '01',
    title: 'Who is she',
    subtitle: 'Fullstack Developer',
    spineImage: 'images/book_01.png',
    spineColor: '#1a1a2e',
    textColor: '#e8ddd0',
    type: 'about',
    image: 'images/profile.JPG',
    content: {
      heading: '사용자의 눈으로,\n개발자의 손으로.',
      body: '퍼블리셔로 시작해 보이는 것을 만들었고, 개발자로 성장하며 작동하는 것을 설계합니다.',
      details: [
        { label: 'Experience', value: '(주)이타즈 · (주)록스 · 아이오랩' },
        { label: 'Education', value: '경성대학교 컴퓨터공학과' },
        { label: 'Certificate', value: '정보처리기사' },
      ],
      email: 'cozyoub@gmail.com',
    },
  },
  {
    id: 'moneylog',
    //number: '02',
    title: 'Moneylog',
    subtitle: '챗봇 기반 스마트 가계부',
    spineImage: 'images/book_02.png',
    spineColor: '#f989b3',
    textColor: '#fff',
    type: 'project',
    slug: 'moneylog',
    image: 'images/dv03.png',
    content: {
      heading: 'moneylog',
      body: '챗봇 기반의 스마트 지출 관리 애플리케이션.\nFlutter와 React를 활용한 크로스 플랫폼 서비스입니다.',
      tech: 'Flutter · Spring Boot · React · JWT · MySQL',
      period: '2024.06.09 ~ 2024.06.19',
      team: '4인 팀 프로젝트',
    },
  },
  {
    id: 'slow-mode',
   //number: '03',
    title: 'Slow Mode',
    subtitle: '습관 트래커',
    spineImage: 'images/book_03.png',
    spineColor: '#56dfb4',
    textColor: '#1a3a2a',
    type: 'project',
    slug: 'slow-mode',
    image: 'images/dv02.png',
    content: {
      heading: '저속노화 습관트래커',
      body: 'Spring Boot 기반 백엔드와 React 프론트엔드를 직접 설계·구현한 풀스택 프로젝트.\n사용자의 일일 습관을 체크하고 월간 통계를 제공합니다.',
      tech: 'Spring Boot · React · JWT · MySQL · JPA',
      period: '2024.11.28 ~ 2024.12.12',
      team: '1인 프로젝트',
    },
  },
  {
    id: 'bookkok',
    //number: '04',
    title: '책콕',
    subtitle: '중고책 거래 플랫폼',
    spineImage: 'images/book_04.png',
    spineColor: '#e8c547',
    textColor: '#2b1f0e',
    type: 'project',
    slug: 'bookkok',
    image: 'images/dv01.png',
    content: {
      heading: '책콕',
      body: 'Spring Boot + Thymeleaf 기반의 중고책 거래 플랫폼.\nUI/UX 설계부터 장바구니·결제·알림 기능까지 구현했습니다.',
      tech: 'Spring Boot · Thymeleaf · JPA · MySQL · GSAP',
      period: '2024.10.30 ~ 2024.11.12',
      team: '4인 팀 프로젝트',
    },
  },
  {
    id: 'work',
    //number: '05',
    title: 'Work',
    subtitle: '퍼블리싱 실무',
    spineImage: 'images/book_05.png',
    spineColor: '#5a6875',
    textColor: '#e8edf2',
    type: 'work',
    image: 'images/pj01.jpg',
    content: {
      heading: 'Work Experience',
      body: '6년간의 웹 퍼블리싱 및 디자인 실무 작업물.\n웹 표준, 반응형 레이아웃, 디자인 시안 기반 UI 구현 경험.',
      items: [
        { title: '부산교육대학교 리뉴얼', desc: 'Web | 디자인 · 퍼블리싱 · 기획' },
        { title: '김해문화재단 리뉴얼', desc: 'Web | 디자인 · 퍼블리싱 · 기획' },
        { title: 'OK저축은행', desc: 'App | 디자인 · 퍼블리싱 · 기획' },
        { title: '델타티서비스', desc: 'Web | 디자인 · 퍼블리싱 · 기획' },
        { title: '호서대학교 학과 개편', desc: 'Web | 디자인 · 퍼블리싱 · 기획' },
      ],
    },
  },
  {
    id: 'contact',
    //number: '06',
    title: 'Contact',
    subtitle: 'Get in touch',
    spineImage: 'images/book_06.png',
    spineColor: '#212529',
    textColor: '#adb5bd',
    type: 'contact',
    content: {
      heading: 'Contact',
      email: 'cozyoub@gmail.com',
      phone: '010.4458.6076',
      github: 'https://github.com/ubzzang',
      github2: 'https://github.com/cozyoub',
    },
  },
];
